### ISSUE TITLE
Integrate FlightGear as Visualizer

### ISSUE THREAD

**Issue by dcmcshan** [Syzygyx/DroneWidgets#12]
Goal is to use FlightGear (http://www.flightgear.org/) as a visualizer for QGC. We already have a vehicle model which I will get to you.  For now, you really just have to focus on having QGC output position and attitude to FlightGear.  Later, we'll have it send other telemetry as well (like motor speed so the props spin...)  For now, just focus on ability for QGC to send FlightGear 6DOF position/attitude

**Comment by BojanKverh** [comment]
I studied the FG protocol of data exchange, will try to make a working prototype tomorrow.
One question though: FG has the ability to read data from file and replay it, so is this the option too, or QGC has to communicate with FG in real time (not that it makes much difference, IMHO)?

**Comment by dcmcshan** [comment]
Realtime.  We want FG to reflect what is in QGC

**Comment by BojanKverh** [comment]
Created a small generic protocol description file (xml/qgc.xml) to use when communicating with FlightGear. When outputing data from FG, this works fine. Inputting does not, and documentation about this particular issue is rubbish and FG itself also does not give any information about what it is receiving on UDP port, so I am stuck for the moment.

**Comment by BojanKverh** [comment]
OK, I figured out how to send parameters from QGC to FlightGear. FG expects data in network order (which is Big Endian), while PC processors are usully Little Endian.
To make it work correctly, FG has to be executed from Linux command line as follows:
fgfs --native-fdm=socket,in,100,,5600,udp --fdm=null

**Comment by dcmcshan** [comment]
Yes... silly wrong endian Intel.  I've been designing embedded systems for over twenty years and it still seems ridiculous to me.

**Comment by BojanKverh** [comment]
Now it is possible to replay QGC log files like log.mavlink with FlightGear. Two minor issues though:
- heading instrument at FG always shows +90 in regards to QGC, even though QGC sends it the correct value (I am not a pilot but AFAIK yaw=0 means heading to the north, while FG instrument will point to the east in this case)
- altitude meter: this one confuses me, because the documentation clearly states that altitude should be sent in meters, but to me it looks like it requires altitude in feet and its instrument shows it in meters...

**Comment by dcmcshan** [comment]
I added "arducopter" directory to the DroneWidgets repo.  You can drop this in your custom airframe folder and it will render the vehicle.  

Do you think you can create a widget for QGC that launches flightgear with the needed arguments to listen to the udp port?  I believe there is already a "HIL simulator" perspective which has a "HIL Config" widget that will start flight gear with the airframe, but it needs different parameters to do what we want it to do...

**Comment by BojanKverh** [comment]
Yes, I believe it can be done.

**Comment by BojanKverh** [comment]
Launching FG can now be done from QGC (Advanced/Launch FlightGear)

**Comment by dcmcshan** [comment]
Need to be able to set path. FlightGear is installed (I am on a mac…)

**Comment by BojanKverh** [comment]
OK, I guess "Launch FlightGear" should open a dialog, where you can select the executable (with its path) and possibly an aircraft, since probably this will not be used only with arducopter?

**Comment by dcmcshan** [comment]
Are you using QGCFlightGearLink::connectSimulation?

It seems to have a bunch of logic for sorting out flightgear launch.

For now, we can default to arducopter

**Comment by BojanKverh** [comment]
No, I did not use that, because I didn't noticed it. Will take a look into it.

**Comment by dcmcshan** [comment]
Of course, it seems that the default HIL Simulation doesn’t actually work on Mac anyways… I will investigate a bit.

**Comment by dcmcshan** [comment]
Launcher aside,

If I do this from the /Applications/FlightGear.app/Contents/MacOS directory, flightgear starts with our model (I copied it into the Aircraft directory)

./fgfs --aircraft=arducopter --native-fdm=socket,in,100,,5600,udp --fdm=null

But seems not to be linked to QGC when I playback.  Is there something else I should have to do?

**Comment by BojanKverh** [comment]
As far as I understood Mac OS X, the FG executable should be  /Applications/FlightGear.app
That's how I now updated the launcher. Please check if it works.

**Comment by dcmcshan** [comment]
That is the application, but if you want to pass arguments, the executable is actually as I mentioned,

/Applications/FlightGear.app/Contents/MacOS/fgfs 

Mac OSX is essentially unix.

**Comment by BojanKverh** [comment]
OK, thanks for that information. I commited the change, I hope this time it works, sorry for misunderstanding.

**Comment by BojanKverh** [comment]
One remark though: if QGC starts sending flight data to FG from the beginning, the FG seems to stay stuck with the Loading scenery message forever. Since there seems to be no precise way to determine, when it is safe to start sending flight data, I implemented a timeout of 20 seconds, which seem to work. So FG will start receiving flight data from QGC only 20 seconds after the FG was launched.

**Comment by dcmcshan** [comment]
Looking through the code, I don’t see how you are sending data to flightgear?  Are you using 
MessageDispatcher::SendUDP()?

It seems to have everything commented out…

**Comment by BojanKverh** [comment]
Yes, through SendUDP. The code which is commented out was used in the beginning, when I was still trying to establish the communication with FG. I just wanted to make sure that this simple example works. Later, I left that code (commented) in, so that I can look back into it in case of any troubles. It can be easily removed of course. But after this commented out code, there are few lines, which actually send the internal m_netFDM object through UDP.

**Comment by dcmcshan** [comment]
I have it up and running, though it appears that flight gear is rendering it underground.  I suspect this is because you are sending it AMSL which is altitude above mean sea level, and flight gear is perhaps expecting AGL (above ground level)

There are several reasons why this might occur, but either way we might should bias altitude so that altitude is somewhat reasonable.

**Comment by BojanKverh** [comment]
I am sending AMSL, because in net_fdm.hxx it is clearly stated, that altitude should be given in meters above sea level. There is another variable there, agl, which is altitude above ground level, but to calculate that, I would need to know the terrain elevation at current position. UAS doesn't tell AGL as far as I know. It does tell relative altitude, which is altitude above the home point elevation. I took this one as AGL for the moment.
