### ISSUE TITLE
Advanced QGC Integration

### ISSUE THREAD

**Issue by dcmcshan** [Syzygyx/DroneWidgets#7]
This is where we "wire up" the gauges in QGC to MAVlink parameters.

**Comment by BojanKverh** [comment]
One question regarding these issue: do we need any other gauges except the Temperature ones?

**Comment by dcmcshan** [comment]
Yes, just added to queue!

**Comment by BojanKverh** [comment]
I will look into integrating MAVlink parameters and gauges tomorrow.

**Comment by BojanKverh** [comment]
Just a quick question before I can continue the work: it looks to me that the application gets the parameter values like speed, altitude, etc. from an object of type MAVLinkDecoder, do you know if that is correct?

**Comment by dcmcshan** [comment]
That might be so.  I’m not super familiar.  The way this works is that MAVLink flows into the app via serial port or socket.  It’s an XML stream containing parameter data.  I’d sorta expect that QGC might store variables internally, but maybe not…

**Comment by BojanKverh** [comment]
I've connected the ground speed message to the AirspeedIndicator and FlightInstrumentsWidget. Since I have no way to check if this works right now, I would kindly ask you to test it and report. If this works, the integration of the rest of the parameters should be quite straightforward once I figure out the name of messages corresponding to the other values.

**Comment by dcmcshan** [comment]
Here’s a log file to read in.  I just found it on the web, so no idea what it actually is…
